version: '3.7'

services:

  arkus:
    build: .
    volumes:
      - ./:/www
      - arkus_packs:/www/public/packs
      - arkus_assets:/www/public/assets
      - arkus-bash:/root/usr
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - RAILS_ENV=${RAILS_ENV:-development}
      - mysql_host=arkus_mysql
    command: /usr/share/rvm/wrappers/ruby-2.7.4/bundle exec rails server -b 0.0.0.0 -p 80 --pid=/tmp/server.pid
    ports:
      - 80:80
    depends_on:
      - arkus_mysql

  arkus_mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: arkus_db
      MYSQL_ROOT_PASSWORD: "j2DXC%&aYxLU"
    ports:
      - 8807:3306
    volumes:
      - arkus-mysql:/var/lib/mysql

volumes:
  arkus-mysql:
  arkus-bash:
  arkus_packs:
  arkus_assets: